template_dir = '~/go/src/github.com/kjnh10/pcl/problem_template'  # if this directory does not exist or not specified, default template directory will be used

[prepare]
  [prepare.custom_hook_command]
  after = 'nvim {dirname} -c "args **/solve.cpp" -c "tab all" +6'

[ppp]
  [ppp.custom_hook_command]
  # after = 'nvim {dirname} -c "args **/solve.cpp" -c "tab all" +6'
  # after = 'nvr --remote-tab {dirname}/codes/solve.cpp {dirname}/test/gen.py'
  after = 'nvr --remote-tab {dirname}/codes/solve.cpp'
  # after = 'code "{dirname}" -g {dirname}/codes/solve.cpp:6 {dirname}/test/gen.py -r'

[submit]
  [submit.default_lang.AtCoder]
  cpp = 'gcc_acl'
  py  = 'py'

  [submit.default_lang.Codeforces]
  cpp = 'gcc'
  py  = 'py'

  [submit.default_lang.yukicoder]
  cpp = 'cpp17'
  py  = 'pypy3'

[test]
  timeout_sec=2
  max_memory=1024

  [test.compile_command] # specify the profile used by default for tt and sb
  configname = 'default'

  [test.compile_command.cpp]  # for tt command, you can change the compile command by --cc option. like 'pcm tt -c 1 --cc v5'
  default = """g++ {srcpath} -o {outpath} \
               -std=c++17 \
               -include /home/koji0708/go/src/github.com/kjnh10/pcl/library/cpp/debug/dump.hpp \
               -I {pcm_dir_path}/lang_library/cplusplus/ac-library \
               -DPCM -Wall -D_GLIBCXX_DEBUG -fuse-ld=gold
            """

  debug = """g++ {srcpath} -o {outpath} \
            -std=c++17 \
            -include /home/koji0708/go/src/github.com/kjnh10/pcl/library/cpp/debug/dump.hpp \
            -I {pcm_dir_path}/lang_library/cplusplus/ac-library \
            -DPCM -Wall -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG -fuse-ld=gold \
            -g
            """

  # how to install clang: https://qiita.com/tekito2/items/0a534781631342f2a3a9
  clang = """/home/llvm/bin/clang++ {srcpath} -o {outpath} \
          -std=c++17 \
          -include /home/koji0708/go/src/github.com/kjnh10/pcl/library/cpp/debug/dump.hpp \
          -I/usr/include/x86_64-linux-gnu/c++/9 \
          -I/usr/include/c++/9 \
          -I {pcm_dir_path}/lang_library/cplusplus/ac-library \
          -DPCM -Wall -D_GLIBCXX_DEBUG -fuse-ld=lld
          """

  detail = """g++ {srcpath} -o {outpath} \
            -std=c++17 \
            -include /home/koji0708/go/src/github.com/kjnh10/pcl/library/cpp/debug/dump.hpp \
            -I {pcm_dir_path}/lang_library/cplusplus/ac-library \
            -DPCM\
            -Wall -Wextra -pedantic -O2 -Wshadow -Wformat=2 -Wfloat-equal -Wconversion -Wlogical-op -Wshift-overflow=2 -Wduplicated-cond -Wcast-qual -Wcast-align -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -D_FORTIFY_SOURCE=2 -fsanitize=address -fsanitize=undefined -fno-sanitize-recover -fstack-protector \
  """

